### ISSUE TITLE
Bad coproduct serialization behaviour with nested messages

### ISSUE THREAD

**Issue by fedefernandez** [btlines/pbdirect#21]
We're having problems using pbdirect for serializing case classes with nested optional arguments. I've reproduced this error with a simple main program. It's very strange because it works in tests but it fails in the main code. (see the [code here](https://github.com/btlines/pbdirect/compare/master...47deg:ff-optional-nested-coproducts)

I've created a new test case in `PBWriterSpec` that works flawlessly:
```scala
    "write a nested empty message to Protobuf" in {
      case class InnerMessage(value: Int)
      case class OuterMessage(text: Option[String], inner: Option[InnerMessage])
      val message = OuterMessage(Some("Hello"), None)
      message.toPB shouldBe Array[Byte](10, 5, 72, 101, 108, 108, 111)
    }
```
But a similar code block fails when is moved to `src/main/` code:
```scala
package pbdirect

object TestToPB extends App {

  case class InnerMessage(value: Int)
  case class OuterMessage(text: Option[String], inner: Option[InnerMessage])
  val message = OuterMessage(Some("Hello"), None)
  val a: Array[Byte] = message.toPB
  val e: Array[Byte] = Array[Byte](10, 5, 72, 101, 108, 108, 111)
  assert(a.sameElements(e))

}
```

We've debugged a bit the problem and found that in the second case, the serialization is adding an extra character at the end:

![screen shot 2018-07-13 at 10 23 38](https://user-images.githubusercontent.com/720923/42760072-7a512060-8909-11e8-8d06-aee1d5bb2b5e.png)

And seems to be a problem related to how shapeless is resolving the coproduct implicits:
*Test case*:
```
--------------prodWriter
--------------A = OuterMessage(Some(Hello),None)
--------------prodWriter

--------------consWriter
-------------- H :: T = Some(Hello) :: None :: HNil
--------------consWriter

--------------4
--------------consWriter
-------------- H :: T = None :: HNil
--------------consWriter

Bytes: 10,5,72,101,108,108,111

[info] PBWriterSpec:
[info] PBWriter
[info] - should write a nested empty message to Protobuf
```

*In the main class case*:

```
--------------prodWriter
--------------A = OuterMessage(Some(Hello),None)
--------------prodWriter

--------------consWriter
-------------- H :: T = Some(Hello) :: None :: HNil
--------------consWriter

--------------coprodWriter
--------------A = Some(Hello)
--------------coprodWriter

--------------cconsWriter
--------------H:+: T = Inr(Inl(Some(Hello)))
--------------cconsWriter

--------------cconsWriter
--------------H:+: T = Inl(Some(Hello))
--------------cconsWriter

--------------prodWriter
--------------A = Some(Hello)
--------------prodWriter

--------------consWriter
-------------- H :: T = Hello :: HNil
--------------consWriter

--------------4
--------------consWriter
-------------- H :: T = None :: HNil
--------------consWriter

--------------coprodWriter
--------------A = None
--------------coprodWriter

--------------cconsWriter
--------------H:+: T = Inl(None)
--------------cconsWriter

--------------prodWriter
--------------A = None
--------------prodWriter

Bytes: 10, 7, 10, 5, 72, 101, 108, 108, 111, 18, 0
```

**Comment by btlines** [comment]
As you have found out your main prog fails to find a writer for `Option[_]` and so it serialises it as a coproduct: `Some[_] :+: None :+: CNil` which is not what you want.

To serialise `Option` correctly you need to `import cats.implicits._` or more specifically `import cats.instances.option._`. (I suppose you have this import clause present in your tests somehow).

The reason is that pbdirect knows how to serialise a functor but for this to work it needs an evidence that `Option` is a `Functor` and this is provided by importing cats implicits.

**Comment by fedefernandez** [comment]
That explains everything. I'll try it and I'll let you know, thanks.

**Comment by fedefernandez** [comment]
Works flawlessly 👍
