### ISSUE TITLE
Diverging implicit expansion for type pbdirect.PBWriter

### ISSUE THREAD

**Issue by eperinan** [btlines/pbdirect#9]
I am trying to serialize two case classes but I am getting the next error:

```
[error] /Users/eperinan/workspace/47deg/open-source-github/freestyle-opscenter/src/main/scala/Main.scala:71:92: diverging implicit expansion for type pbdirect.PBWriter[freestyle.Main.Metric :: List[freestyle.Main.Metric] :: shapeless.HNil]
[error] starting with method enumerationWriter in trait PBWriterImplicits
[error]     Binary(MetricsList(List(Metric("metric", "microservices", "node", 12.toFloat, 12345))).toPB)

```
Here you can check the app that I am building and the two case class.

```
object Main extends App {

  import cats.instances.list._
  import pbdirect._

  case class Metric(metric: String, microservice: String, node: String, value: Float, count: Int)
  case class MetricsList(metrics: List[Metric])

  println(
    Binary(MetricsList(List(Metric("metric", "microservices", "node", 12.toFloat, 12345))).toPB)
  )
}
```

I took a look to the code and we have implicits for all of them. Do you know which could be the problem ?

Thanks so much!

**Comment by btlines** [comment]
Thanks for reporting it.
`diverging implicit expansion` happens when the compiler thinks the implicit resolution isn't converging fast enough.
I suppose there is a missing `Lazy` somewhere in the implicit methods signatures.
Let me have a look.
